CREATE DATABASE IF NOT EXISTS `todo_app` CHARSET utf8mb4 COLLATE utf8mb4_bin;

USE `todo_app`;

DROP TABLE IF EXISTS todo;

CREATE TABLE IF NOT EXISTS `todo` (
  `id` integer NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
